#!/bin/sh

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias tree="tree -A"
alias treed="tree -d"
alias tree1="tree -d -L 1"
alias tree2="tree -d -L 2"

if type "exa" > /dev/null; then
    alias l='exa -l --icons --header --long --git --color=always --group-directories-first --sort=ext' # my preferred listing
    alias la='exa -a --header --long --git --color=always --group-directories-first --sort=ext'  # all files and dirs
    alias ll='exa -lh --links --blocks --accessed --created --header --long --git --color=always --modified --group-directories-first'  # long format
    alias ld='exa -D --color=always --group-directories-first --sort=ext' # my preferred listing
    alias lt='exa -aT --color=always --group-directories-first' # tree listing
    alias tree="exa --tree"
    alias tree1="exa --tree --level=1 --long"
    alias tree2="exa --tree --level=2 --long"
fi

# List declared aliases, functions, paths
alias aliases="alias | sed 's/=.*//'"
alias functions="declare -f | grep '^[a-z].* ()' | sed 's/{$//'"
alias paths='echo -e ${PATH//:/\\n}'

# firewall management
alias port-forward-enable="echo 'rdr pass inet proto tcp from any to any port 2376 -> 127.0.0.1 port 2376' | sudo pfctl -ef -"
alias port-forward-disable="sudo pfctl -F all -f /etc/pf.conf"
alias port-forward-list="sudo pfctl -s nat"

# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec $SHELL -l"

# dotdrop
alias dot="$HOME/.dotfiles/dotdrop.sh --cfg=$HOME/.dotfiles/config.yaml"

# nvm
alias loadnvm='[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias iplocal="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"

# Show network connections
alias n.connections='lsof -l -i +L -R -V'
alias n.established='lsof -l -i +L -R -V | grep ESTABLISHED'
alias n.externalip='curl -s http://checkip.dyndns.org/ | sed "s/[a-zA-Z<>/ :]//g"'
alias n.internalip="ifconfig en0 | egrep -o '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)'"

# recursive dos2unix in current directory
alias dos2lf='dos2unix `find ./ -type f`'

# Flush the DNS on Mac
alias dnsflush='dscacheutil -flushcache'

# Disable Spotlight
alias spotoff="sudo mdutil -a -i off"

# Enable Spotlight
alias spoton="sudo mdutil -a -i on"

