#!/usr/bin/env sh

# close focused window
alt - w : yabai tiling::window --close

# Moving windows
shift + alt - h : yabai -m window --warp west
shift + alt - j : yabai -m window --warp south
shift + alt - k : yabai -m window --warp north
shift + alt - l : yabai -m window --warp east

# Navigation
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# Resize windows
lctrl + alt - h : \
    yabai -m window --resize left:-80:0 ; \
    yabai -m window --resize right:-80:0

lctrl + alt - j : \
    yabai -m window --resize bottom:0:80 ; \
    yabai -m window --resize top:0:80

lctrl + alt - k : \
    yabai -m window --resize top:0:-80 ; \
    yabai -m window --resize bottom:0:-80

lctrl + alt - l : \
    yabai -m window --resize right:80:0 ; \
    yabai -m window --resize left:80:0

# Move focus container to workspace
shift + alt - m : yabai -m window --space last && yabai -m space --focus last
shift + alt - p : yabai -m window --space prev && yabai -m space --focus prev
shift + alt - n : yabai -m window --space next && yabai -m space --focus next
shift + alt - 1 : yabai -m window --space 1 && yabai -m space --focus 1
shift + alt - 2 : yabai -m window --space 2 && yabai -m space --focus 2
shift + alt - 3 : yabai -m window --space 3 && yabai -m space --focus 3
shift + alt - 4 : yabai -m window --space 4 && yabai -m space --focus 4
shift + alt - 5 : yabai -m window --space 5 && yabai -m space --focus 5
shift + alt - 6 : yabai -m window --space 6 && yabai -m space --focus 6

# Move windows but no FOCUS
hyper - 1 : yabai -m window --space 1
hyper - 2 : yabai -m window --space 2
hyper - 3 : yabai -m window --space 3
hyper - 4 : yabai -m window --space 4
hyper - 5 : yabai -m window --space 5
hyper - 6 : yabai -m window --space 6

# Float and center window
# grid <rows>:<cols>:<start-x>:<start-y>:<width>:<height>
shift + alt - c : yabai -m window --toggle float;\
                  yabai -m window --toggle zoom-fullscreen
                  # yabai -m window --grid 1:1:0:0:1:1
# Float & center
# <rows>:<cols>:<start-x>:<start-y>:<width>:<height>
hyper - c: yabai -m window --toggle float && \
           yabai -m window --grid 1:1:1:1:1:2

# toggle window float
shift + alt - t : yabai -m window --toggle float --grid 4:4:1:1:2:2

# Equalize size of windows
lctrl + alt - 0 : yabai -m space --balance

# Enable / Disable gaps in current workspace
lctrl + alt - g : yabai -m space --toggle padding; yabai -m space --toggle gap

# Rotate windows clockwise and anticlockwise
alt - r         : yabai -m space --rotate 90
shift + alt - r : yabai -m space --rotate 270

# Rotate on X and Y Axis
shift + alt - x : yabai -m space --mirror x-axis
shift + alt - y : yabai -m space --mirror y-axis

# Set insertion point for focused container
shift + lctrl + alt - h : yabai -m window --insert west
shift + lctrl + alt - j : yabai -m window --insert south
shift + lctrl + alt - k : yabai -m window --insert north
shift + lctrl + alt - l : yabai -m window --insert east

# Float / Unfloat window
shift + alt - space : yabai -m window --toggle float

# Float all windows
shift + lctrl + alt - f : yabai -m config layout float

# Focus on workspace
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5

# Focus space focused before the current one (so you can alternate)
alt - m : yabai -m space --focus recent

# Focus previous space by mission-control index
alt - p : yabai -m space --focus prev

# Focus next space by mission-control index
alt - n : yabai -m space --focus next

# Create space on the active display
alt - c : yabai -m space --create

# Delete focused space and focus first space on display
alt - d : yabai -m space --destroy

# Switch layout (bsp|float)
hyper - b: yabai -m space --layout bsp
hyper - f: yabai -m space --layout float

# Swap
hyper - up: yabai -m window --swap west
hyper - down: yabai -m window --swap east

# move spaces
# '['
hyper - 0x21 : yabai -m space --move prev
# ']'
hyper - 0x1E : yabai -m space --move next

# rotate layout clockwise
shift + alt - r : yabai -m space --rotate 270

# flip along y-axis
shift + alt - y : yabai -m space --mirror y-axis

# flip along x-axis
shift + alt - x : yabai -m space --mirror x-axis

# Restart Yabai
shift + lctrl + alt - r :
    /usr/bin/env osascript <<< \
        "display notification \"Restarting Yabai\" with title \"Yabai\""; \
    launchctl kickstart -k "gui/${UID}/org.nixos.yabai"
    # launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"
