#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus
yabai -m config window_placement second_child
# yabai -m config window_topmost               off
yabai -m config window_opacity on
yabai -m config window_opacity_duration 1.0
yabai -m config window_shadow on
yabai -m config window_border on
yabai -m config window_border_width 6
yabai -m config window_border_radius -1.0
yabai -m config active_window_border_color 0xffcc241d # 0xffb6d12c
yabai -m config normal_window_border_color 0xff505050
yabai -m config insert_window_border_color 0xffd75f5f
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 10
yabai -m config bottom_padding 30
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# create at lease 8 spaces
# yabai -m space --create
# yabai -m space --create
# yabai -m space --create
# yabai -m space --create
# yabai -m space --create
# yabai -m space --create
# yabai -m space --create

# mark spaces respectively
yabai -m space 1 --label main
yabai -m space 2 --label code
yabai -m space 3 --label browsing
yabai -m space 4 --label productivity
yabai -m space 5 --label work-comm
yabai -m space 6 --label comm
yabai -m space 7 --label other

# example how to send apps to specific windows
# for wid in $(yabai -m query --windows | jq '.[] | select(.app | IN("Notion", "TickTick")) | .id'); do yabai -m window $wid --space 5; done

# NOTE: come up with different rules when on working machine
# Rules
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^AirBuddy$" sticky=on layer=above manage=off
yabai -m rule --add app="^iStat $" sticky=on layer=above manage=off
yabai -m rule --add app="CleanShot X" sticky=off layer=above manage=off
yabai -m rule --add app="^TickTick$" sticky=off layer=above manage=off
yabai -m rule --add app="^Rize$" sticky=off layer=above manage=off
yabai -m rule --add app="^Raycast$" sticky=off layer=above manage=off
yabai -m rule --add app="One Switch" sticky=off layer=above manage=off
yabai -m rule --add app="^Browserosaurus$" sticky=off layer=above manage=off
yabai -m rule --add app="^Box$" sticky=off layer=above manage=off
yabai -m rule --add app="Bartender 4" sticky=off layer=above manage=off
#
yabai -m rule --add app="^Alacritty" space=main
yabai -m rule --add app="^Google" space=main
#
yabai -m rule --add app="^Code" space=code
yabai -m rule --add app="^Github Desktop" space=code
#
yabai -m rule --add app="^Firefox" space=browsing
yabai -m rule --add app="^Safari" space=browsing
#
yabai -m rule --add app="^TickTick$" space=productivity
yabai -m rule --add app="^Notion$" space=productivity
yabai -m rule --add app="^Obsidian$" space=productivity
#
yabai -m rule --add app="^Microsoft Outlook" space=work-comm
yabai -m rule --add app="^Microsoft Teams" space=work-comm
yabai -m rule --add app="^Slack" space=work-comm
#
# yabai -m rule --add app="^WeChat$" grid=1:1:0:0:1:1 manage=off space=comm
# yabai -m rule --add app="^WhatsApp" space=comm
# yabai -m rule --add app="^Mail" space=comm
# yabai -m rule --add app="^Messages" space=comm
# yabai -m rule --add app="^Discord" space=comm

echo "yabai configuration loaded.."
